version: "3.7"

services:
    dev:
        image: petercha2000/env:42seoul
        container_name: 42seoul
        restart: always
        ports:
            - 9922:22
        volumes:
            - ~/Dev/Projects:/home/dhuni/Dev/Projects
