version: "3.7"

services:
  42seoul:
    image: petercha2000/env:42seoul
    container_name: 42seoul
    build:
      context: .
      dockerfile: 42seoul.Dockerfile
    platform: linux/amd64
    ports:
      - 7782:22
    volumes:
      - ~/Dev/Projects:/home/dhuni/Dev/Projects
    restart: always
