version: "3.7"

services:
  dev:
    image: petercha2000/env:42seoul
    network_mode: host
    ports:
      - 7782:22
    volumes:
      - ~/Dev/Projects:/home/dhuni/Dev/Projects
    stdin_open: true
    tty: true
